---
title: "MitoSignatures"
author: "Isabel Duarte"
date: "2023-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warnings=FALSE, cache = FALSE)

library(here)
library(tidyverse)
library(mitocarta)

```

## Function to plot the most extreme DEGs

```{r boxplot_funct, eval=TRUE}

## Function to plot the counts for extreme LFC differentially expressed genes

plot_extreme_degs <- function (diff_exprs_list,
                               n_degs_to_plot = 20,
                               mito_yes_no = "no") {
  
  #### PLOTING FUNCTIONS | START ####
  boxplot_organ <-
    function (counts_data, my_title = "Boxplot per Gene") {
      ggplot(counts_data, aes(x = organ, y = log2(counts + 1))) +
        geom_boxplot(aes(color = metabolic_rate)) +
        labs(x = "Organs", y = "Log2 Gene Counts", title = my_title) +
        theme(axis.text.x = element_text(
          angle = 90,
          vjust = 0.5,
          hjust = 1
        )) +
        theme(legend.position = "bottom") +
        facet_wrap(vars(gene_id), scales = "free_y")
    }
  
  boxplot_organ_and_cancer_status <-
    function (counts_data, my_title = "Boxplot per Gene and Cancer Status") {
      ggplot(counts_data, aes(
        x = interaction(organ, cancer_status),
        y = log2(counts + 1)
      )) +
        geom_boxplot(aes(color = metabolic_rate)) +
        labs(x = "Organs", y = "Log2 Gene Counts", title = my_title) +
        theme(axis.text.x = element_text(
          angle = 90,
          vjust = 0.5,
          hjust = 1
        )) +
        theme(legend.position = "bottom") +
        facet_wrap(vars(gene_id), scales = "free_y")
    }
  #### PLOTING FUNCTIONS | END ####
  
  
  #### Main Function ####
  
  # Create list to hold objets from this analysis
  deg_analysis <- list()
  plots <- list()
  
  # Get the dataset name
  dataset_name = rlang::as_label(rlang::enexpr(diff_exprs_list))
  
  ###
  ### Filter mitochondrial genes only
  ###
  
  if (mito_yes_no == "yes") {
    ### Mitocarta Gene IDs
    # Get all mitocarta ensembl ids (including the ones with several ids separated by pipe)
    deg_analysis$mitocarta_gene_ids <-
      unlist(
        strsplit(
          mitocarta::mitocarta_data$A_Human_MitoCarta3$EnsemblGeneID_mapping_version_20200130,
          "\\|"
        )
      )
    
    ### Mitochondrial DEGs in toptable data
    # Get all toptable ensembl ids without the .version (because mitocarta does not have it)
    deg_analysis$toptable_gene_ids <-
      gsub(
        pattern = "(ENSG\\d+)(\\.\\d+)?",
        replacement = "\\1",
        row.names(diff_exprs_list$topGenes$table)
      )
    
    # Filter toptable_gene_ids to include only mitocarta genes
    deg_analysis$mito_toptable_gene_ids <-
      deg_analysis$toptable_gene_ids[deg_analysis$toptable_gene_ids %in% deg_analysis$mitocarta_gene_ids]
    
    # Slice DEGS toptable to include only Mitochondrial top/bottom n_degs_to_plot, sorted by LFC
      # Important note: Subseting matrices using [] does partial matching for the rownames 
      # (so it does not match the .version)
    
    # Top genes with negative Log Fold Change
    deg_analysis$low_exprs <-
      diff_exprs_list$topGenes$table[deg_analysis$mito_toptable_gene_ids, ] %>%
      dplyr::arrange(logFC) %>%
      dplyr::slice_head (n = n_degs_to_plot)
    
    # Top genes with positive Log Fold Change
    deg_analysis$high_exprs <-
      diff_exprs_list$topGenes$table[deg_analysis$mito_toptable_gene_ids, ] %>%
      dplyr::arrange(logFC) %>%
      dplyr::slice_tail (n = n_degs_to_plot)
  }
  
  ##
  ## Do not filter mitochondrial genes
  ##
  
  if (mito_yes_no == "no") {
    ### Slice DEGS toptable to include only the top/bottom n_degs_to_plot, sorted by LFC
    # Top genes with negative Log Fold Change
    deg_analysis$low_exprs <- diff_exprs_list$topGenes$table %>%
      dplyr::arrange(logFC) %>%
      dplyr::slice_head (n = n_degs_to_plot)
    
    # Top genes with positive Log Fold Change
    deg_analysis$high_exprs <- diff_exprs_list$topGenes$table %>%
      dplyr::arrange(logFC) %>%
      dplyr::slice_tail (n = n_degs_to_plot)
  }
  
  ###
  ### Common steps
  ###
  
  # Bind the top high and low DEGs
  deg_analysis$extreme_de <-
    dplyr::bind_rows (deg_analysis$low_exprs, deg_analysis$high_exprs)
  
  
  ### Create  a tidy dataframe with count values and metadata for selected DEGs
  # Add the metadata to the counts table (filtered by the genes with extreme LFC)
  deg_analysis$extreme_de_counts_metadata <-
    diff_exprs_list$data_clean$combined_counts %>%
    filter(gene_id %in% row.names(deg_analysis$extreme_de)) %>%
    pivot_longer(names_to = "sample_id",
                 values_to = "counts",
                 cols = -1) %>%
    left_join(., diff_exprs_list$data_clean$metadata, by = "sample_id")
  
  ###
  ### Plot counts for selected DEGs
  ###
  
  # Boxplot per organ faceted by gene
  boxplot_organ(
    counts_data = deg_analysis$extreme_de_counts_metadata,
    my_title = ifelse(
      mito_yes_no == "yes",
      "Extreme Mitochondrial DEGs",
      "Extreme DEGs"
    )
  ) ->
    plots$p1_box_gene
  
  # Boxplot per organ per cancer status faceted by gene
  boxplot_organ_and_cancer_status(
    counts_data = deg_analysis$extreme_de_counts_metadata,
    my_title = ifelse(
      mito_yes_no == "yes",
      paste0("Extreme Mitochondrial DEGs | ", dataset_name),
      paste0("Extreme DEGs | ", dataset_name)
    )
  ) ->
    plots$p2_box_gene_cancer
  
  ### Return the list with the analysis and plots
  return(plots)
}
```


```{r load_data, eval=FALSE}

## NOTE | Do NOT KNIT this file because the loading of the RDS files is too slow and the knitting fails
## NOTE 2 | Cannot save the de_boxplots object to disk because it is HUGE (lobstr::obj_size(de_boxplots) is 33.13 GB)

## Load the DE data
gtex_de <- readRDS(file = here("data/analysis/gtex_de.RDS"))
tcga_de <- readRDS(file = here("data/analysis/tcga_de.RDS"))
combined_de_no_interaction <- readRDS(file = here("data/analysis/combined_de_no_interaction.RDS"))
combined_de_only_interaction <- readRDS(file = here("data/analysis/combined_de_only_interaction.RDS"))
combined_de_with_interaction <- readRDS(file = here("data/analysis/combined_de_with_interaction.RDS"))
```


## Creat Expression Boxplots of the most extreme DEGs and Save to PDF | All genes & Mitochondrial genes 

```{r boxplots, dependson="boxplot_funct", eval=FALSE}
#
##
### Expression level boxplots
##
#

## Create the list to save the boxplot data
de_boxplots <- list()

## Call the function for DEG files for each dataset
de_boxplots$gtex$all <- 
  plot_extreme_degs(diff_exprs_list = gtex_de,
                    n_degs_to_plot = 10,
                    mito_yes_no = "no")
de_boxplots$tcga$all <- 
  plot_extreme_degs(diff_exprs_list = tcga_de,
                    n_degs_to_plot = 10,
                    mito_yes_no = "no")
de_boxplots$combined_de_no_interaction$all <- 
  plot_extreme_degs(diff_exprs_list = combined_de_no_interaction,
                    n_degs_to_plot = 10,
                    mito_yes_no = "no")
de_boxplots$combined_de_only_interaction$all <- 
  plot_extreme_degs(diff_exprs_list = combined_de_only_interaction,
                    n_degs_to_plot = 10,
                    mito_yes_no = "no")
de_boxplots$combined_de_with_interaction$all <- 
  plot_extreme_degs(diff_exprs_list = combined_de_with_interaction,
                    n_degs_to_plot = 10,
                    mito_yes_no = "no")

## Call the function for DEG files for each dataset only for mitochondrial genes
de_boxplots$gtex$mito <- 
  plot_extreme_degs(diff_exprs_list = gtex_de,
                    n_degs_to_plot = 10,
                    mito_yes_no = "yes")
de_boxplots$tcga$mito <- 
  plot_extreme_degs(diff_exprs_list = tcga_de,
                    n_degs_to_plot = 10,
                    mito_yes_no = "yes")
de_boxplots$combined_de_no_interaction$mito <- 
  plot_extreme_degs(diff_exprs_list = combined_de_no_interaction,
                    n_degs_to_plot = 10,
                    mito_yes_no = "yes")
de_boxplots$combined_de_only_interaction$mito <- 
  plot_extreme_degs(diff_exprs_list = combined_de_only_interaction,
                    n_degs_to_plot = 10,
                    mito_yes_no = "yes")
de_boxplots$combined_de_with_interaction$mito <- 
  plot_extreme_degs(diff_exprs_list = combined_de_with_interaction,
                    n_degs_to_plot = 10,
                    mito_yes_no = "yes")

#
##
### Export the boxplots to png
##
#

## Boxplots all genes
ggsave(file=here("analysis_output/gtex_extreme_degs_boxplot.png"),
    plot = de_boxplots$gtex$all$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    ) 

ggsave(file=here("analysis_output/tcga_extreme_degs_boxplot.png"),
    plot = de_boxplots$tcga$all$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

ggsave(file=here("analysis_output/comb_NO_interac_extreme_degs_boxplot.png"),
    plot = de_boxplots$combined_de_no_interaction$all$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

ggsave(file=here("analysis_output/comb_ONLY_interac_extreme_degs_boxplot.png"),
    plot = de_boxplots$combined_de_only_interaction$all$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

ggsave(file=here("analysis_output/comb_WITH_interac_extreme_degs_boxplot.png"),
    plot = de_boxplots$combined_de_with_interaction$all$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )


## Boxplots mitochondrial genes
ggsave(file=here("analysis_output/gtex_mito_degs_boxplot.png"),
    plot = de_boxplots$gtex$mito$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    ) 

ggsave(file=here("analysis_output/tcga_mito_degs_boxplot.png"),
    plot = de_boxplots$tcga$mito$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

ggsave(file=here("analysis_output/comb_NO_interac_mito_degs_boxplot.png"),
    plot = de_boxplots$combined_de_no_interaction$mito$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

ggsave(file=here("analysis_output/comb_ONLY_interac_mito_degs_boxplot.png"),
    plot = de_boxplots$combined_de_only_interaction$mito$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

ggsave(file=here("analysis_output/comb_WITH_interac_mito_degs_boxplot.png"),
    plot = de_boxplots$combined_de_with_interaction$mito$p2_box_gene_cancer, 
    device="png", width = 29.7, height = 21, units = "cm" 
    )

```


## Create tables for Coefficients of the different datasets and linear models

```{r coef, dependson="load_data", eval=TRUE}
#
##
### Coefficients | Merge data to compare
##
#

# Create list
lrt_coef_df <- list()
lrt_coef_df$separate <- list()
lrt_coef_df$merged <- list()

# Get coefficients in data frame format and change the column names to include the dataset name (except the gene_id column)
lrt_coef_df$separate$gtex <- 
  data.frame(gene_id = rownames(gtex_de$lrt$coefficients), 
             gtex_de$lrt$coefficients, row.names = NULL)
colnames (lrt_coef_df$separate$gtex)[-1] <- paste0(colnames(lrt_coef_df$separate$gtex)[-1], "_gtex")

lrt_coef_df$separate$tcga <- 
  data.frame(gene_id = rownames(tcga_de$lrt$coefficients), 
             tcga_de$lrt$coefficients, row.names = NULL)
colnames (lrt_coef_df$separate$tcga)[-1] <- paste0(colnames(lrt_coef_df$separate$tcga)[-1], "_tcga")

lrt_coef_df$separate$combined_no_interaction <- 
  data.frame(gene_id = rownames(combined_de_no_interaction$lrt$coefficients), 
             combined_de_no_interaction$lrt$coefficients, row.names = NULL)
colnames (lrt_coef_df$separate$combined_no_interaction)[-1] <- paste0(colnames(lrt_coef_df$separate$combined_no_interaction)[-1], "_comb_NO")

lrt_coef_df$separate$combined_only_interaction <- 
  data.frame(gene_id = rownames(combined_de_only_interaction$lrt$coefficients), 
             combined_de_only_interaction$lrt$coefficients, row.names = NULL)
colnames (lrt_coef_df$separate$combined_only_interaction)[-1] <- paste0(colnames(lrt_coef_df$separate$combined_only_interaction)[-1], "_comb_ONLY")

lrt_coef_df$separate$combined_with_interaction <- 
  data.frame(gene_id = rownames(combined_de_with_interaction$lrt$coefficients), 
             combined_de_with_interaction$lrt$coefficients, row.names = NULL)
colnames (lrt_coef_df$separate$combined_with_interaction)[-1] <- paste0(colnames(lrt_coef_df$separate$combined_with_interaction)[-1], "_comb_WITH")


# Merge all dataframes by common gene ids
lrt_coef_df$merged$wide <- Reduce(function(x,y) inner_join (x,y, by="gene_id"), lrt_coef_df$separate)


# Pivot the dataframe to make the table tidy
lrt_coef_df$merged$long <- lrt_coef_df$merged$wide %>%
  pivot_longer(cols = !gene_id,
               cols_vary = "slowest",
               names_to = "coeff_name",
               values_to = "coeff_value") %>%
  mutate(coeff_name = factor(coeff_name,
                                levels = colnames(lrt_coef_df$merged$wide)[-1]))

## Save the coefficient tables
saveRDS(lrt_coef_df$merged, file = here("data/analysis/lrt_coef_df_merged.RDS"))

```

## Create tables of  LFC and CPMs of the different datasets and linear models

```{r top_genes, dependson="load_data", eval=TRUE}

#
##
### Top genes | Merge data to compare
##
#

# Create list
top_genes_df <- list()
top_genes_df$separate <- list()
top_genes_df$merged <- list()

# Get top genes table and change the column names to include the dataset name (except the gene_id column)
top_genes_df$separate$gtex <- 
  data.frame(gene_id = rownames(gtex_de$topGenes$table), 
             gtex_de$topGenes$table, row.names = NULL)
colnames (top_genes_df$separate$gtex)[-1] <- paste0(colnames(top_genes_df$separate$gtex)[-1], "_gtex")

top_genes_df$separate$tcga <- 
  data.frame(gene_id = rownames(tcga_de$topGenes$table), 
             tcga_de$topGenes$table, row.names = NULL)
colnames (top_genes_df$separate$tcga)[-1] <- paste0(colnames(top_genes_df$separate$tcga)[-1], "_tcga")

top_genes_df$separate$combined_no_interaction <- 
  data.frame(gene_id = rownames(combined_de_no_interaction$topGenes$table), 
             combined_de_no_interaction$topGenes$table, row.names = NULL)
colnames (top_genes_df$separate$combined_no_interaction)[-1] <- paste0(colnames(top_genes_df$separate$combined_no_interaction)[-1], "_comb_NO")

top_genes_df$separate$combined_only_interaction <- 
  data.frame(gene_id = rownames(combined_de_only_interaction$topGenes$table), 
             combined_de_only_interaction$topGenes$table, row.names = NULL)
colnames (top_genes_df$separate$combined_only_interaction)[-1] <- paste0(colnames(top_genes_df$separate$combined_only_interaction)[-1], "_comb_ONLY")

top_genes_df$separate$combined_with_interaction <- 
  data.frame(gene_id = rownames(combined_de_with_interaction$topGenes$table), 
             combined_de_with_interaction$topGenes$table, row.names = NULL)
colnames (top_genes_df$separate$combined_with_interaction)[-1] <- paste0(colnames(top_genes_df$separate$combined_with_interaction)[-1], "_comb_WITH")


# Merge all dataframes by common gene ids
top_genes_df$merged$wide <- Reduce(function(x,y) inner_join (x,y, by="gene_id"), top_genes_df$separate)


# Pivot LogFC and LogCPM data to make it tidy

top_genes_df$merged$logFC_long <-
  top_genes_df$merged$wide %>%
  select(gene_id, contains("LogFC")) %>%
  pivot_longer(cols = !gene_id, 
               names_to = "dataset_model", 
               values_to = "LogFC",
               cols_vary = "fastest") %>%
  mutate(dataset_model = factor(dataset_model,
                                levels = c("logFC_gtex","logFC_tcga",
                                           "logFC_comb_NO",
                                           "logFC_comb_ONLY",
                                           "logFC_comb_WITH") ) )
  
top_genes_df$merged$logCPM_long <-
  top_genes_df$merged$wide %>%
  select(gene_id, contains("LogCPM")) %>%
  pivot_longer(cols = !gene_id, 
               names_to = "dataset_model", 
               values_to = "LogCPM",
               cols_vary = "fastest") %>%
  mutate(dataset_model = factor(dataset_model,
                                levels = c("logCPM_gtex","logCPM_tcga",
                                           "logCPM_comb_NO",
                                           "logCPM_comb_ONLY",
                                           "logCPM_comb_WITH") ) )

top_genes_df$merged$FDR_long <-
  top_genes_df$merged$wide %>%
  select(gene_id, contains("FDR")) %>%
  pivot_longer(cols = !gene_id, 
               names_to = "dataset_model", 
               values_to = "FDR",
               cols_vary = "fastest") %>%
  mutate(dataset_model = factor(dataset_model,
                                levels = c("FDR_gtex","FDR_tcga",
                                           "FDR_comb_NO",
                                           "FDR_comb_ONLY",
                                           "FDR_comb_WITH") ) )

## Save the top genes tables
saveRDS(top_genes_df$merged, file = here("data/analysis/top_genes_df_merged.RDS"))

```



